
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += img/clouds.cpp
SRC += img/flag.cpp
SRC += img/mast.cpp

# Makefile includes
include ../../Makefile.inc
