
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += ANTS/ants.cpp
SRC += ATOMS/atoms.cpp
SRC += EGGS/eggs.cpp
SRC += FIFTEEN/fifteen.cpp
SRC += FLAPPY/flappy.cpp
SRC += GHOSTRAC/ghostracing.cpp
SRC += CHESS/chess.cpp
SRC += LIFE/life.cpp
SRC += MAZE/maze.cpp
SRC += PACMAN/pacman.cpp
SRC += RAPTOR/raptor.cpp
SRC += SOKOBAN/sokoban.cpp
SRC += TETRIS/tetris.cpp
SRC += TRAIN/train.cpp
SRC += TVTENNIS/tvtennis.cpp
SRC += VEGASLOT/vegaslot.cpp

# Makefile includes
include ../../Makefile.inc
