
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += src/game.cpp

SRC += img/background.cpp
SRC += img/blacksreds.cpp
SRC += img/cards.cpp
SRC += img/castle.cpp
SRC += img/cloud.cpp
SRC += img/cursor.cpp
SRC += img/fence.cpp
SRC += img/flags.cpp
SRC += img/grass.cpp
SRC += img/open.cpp
SRC += img/open_sel.cpp
SRC += img/open_sel2.cpp
SRC += img/shadow.cpp
SRC += img/state.cpp
SRC += img/title.cpp
SRC += img/title2.cpp
SRC += img/trumpet.cpp
SRC += img/win.cpp

SRC += snd/applause.cpp
SRC += snd/birds.cpp
SRC += snd/build_castle.cpp
SRC += snd/build_fence.cpp
SRC += snd/card.cpp
SRC += snd/curse.cpp
SRC += snd/decrease_stocks.cpp
SRC += snd/fanfares.cpp
SRC += snd/increase_power.cpp
SRC += snd/increase_stocks.cpp
SRC += snd/ruin_castle.cpp
SRC += snd/ruin_fence.cpp

# Makefile includes
include ../../Makefile.inc
