# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/one_wire.cpp
SRC += src/main.cpp
SRC += img/images.cpp

TARGET=DS18B20
DEVICE=picopad10
DEVCLASS=picopad
DEVDIR=!PicoPad10

# Makefile includes
include ../../../Makefile.inc
