@echo off                     
PicoPadImg background.bmp     background.cpp     BackgroundImg
PicoPadImg blacksreds.bmp     blacksreds.cpp     BlacksRedsImg
PicoPadImg cards.bmp          cards.cpp          CardsImg
PicoPadImg castle.bmp         castle.cpp         CastleImg
PicoPadImg cloud.bmp          cloud.cpp          CloudImg
PicoPadImg cursor.bmp         cursor.cpp         CursorImg
PicoPadImg fence.bmp          fence.cpp          FenceImg
PicoPadImg flags.bmp          flags.cpp          FlagsImg
PicoPadImg grass.bmp          grass.cpp          GrassImg
PicoPadImg open.bmp           open.cpp           OpenImg
PicoPadImg open_sel.bmp       open_sel.cpp       OpenSelImg
PicoPadImg open_sel2.bmp      open_sel2.cpp      OpenSel2Img
PicoPadImg shadow.bmp         shadow.cpp         ShadowImg
PicoPadImg state.bmp          state.cpp          StateImg
PicoPadImg title.bmp          title.cpp          TitleImg
PicoPadImg title2.bmp         title2.cpp         Title2Img
PicoPadImg trumpet.bmp        trumpet.cpp        TrumpetImg
PicoPadImg win.bmp            win.cpp            WinImg
