
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/landscape.cpp
SRC += img/shadows.cpp
SRC += img/sprites.cpp
SRC += img/tiles.cpp

SRC += snd/artillery.cpp
SRC += snd/blackhole.cpp
SRC += snd/blackhole2.cpp
SRC += snd/explosion.cpp
SRC += snd/fail.cpp
SRC += snd/greenrocket.cpp
SRC += snd/laser.cpp
SRC += snd/levelup.cpp
SRC += snd/lost.cpp
SRC += snd/machinegun.cpp
SRC += snd/silverrocket.cpp
SRC += snd/sonar.cpp

# Makefile includes
include ../../Makefile.inc
