
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += img/earth1.cpp
SRC += img/earth2.cpp

# Makefile includes
include ../../Makefile.inc
