
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += src/Table.cpp

SRC += img/back.cpp
SRC += img/symbols.cpp
SRC += img/blur.cpp
SRC += img/digits.cpp

SRC += snd/autooff.cpp
SRC += snd/autoon.cpp
SRC += snd/cash.cpp
SRC += snd/out.cpp
SRC += snd/reel.cpp
SRC += snd/risklost.cpp
SRC += snd/riskwin.cpp
SRC += snd/start.cpp
SRC += snd/stop.cpp
SRC += snd/toss.cpp
SRC += snd/transfer.cpp
SRC += snd/win.cpp

# Makefile includes
include ../../Makefile.inc
