
# ASM source files
ASRC += 

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += src/levels.cpp
SRC += src/game.cpp

SRC += img/tiles.cpp

SRC += snd/collect.cpp
SRC += snd/crash.cpp
SRC += snd/step.cpp
SRC += snd/success.cpp

# Makefile includes
include ../../Makefile.inc
