
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += src/bme280.cpp
SRC += img/images.cpp

TARGET=BME280
DEVICE=picopad10
DEVCLASS=picopad
DEVDIR=!PicoPad10

# Makefile includes
include ../../../Makefile.inc
