
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += src/game.cpp
SRC += src/select.cpp

SRC += src/levels.cpp
SRC += src/levels_rabbit.cpp
SRC += src/levels_peloux.cpp
SRC += src/levels_murase.cpp
SRC += src/levels_martel.cpp
SRC += src/levels_grigor.cpp
SRC += src/levels_haywood.cpp
SRC += src/levels_holland.cpp
SRC += src/levels_skinner.cpp
SRC += src/levels_sladkey.cpp
SRC += src/levels_damgaard.cpp
SRC += src/levels_loma.cpp
SRC += src/levels_domenech.cpp
SRC += src/levels_dzekic.cpp

SRC += img/tiles4.cpp
SRC += img/tiles8.cpp
SRC += img/tiles12.cpp
SRC += img/tiles16.cpp
SRC += img/tiles20.cpp
SRC += img/tiles24.cpp
SRC += img/tiles28.cpp
SRC += img/tiles32.cpp
SRC += snd/yippee.cpp

# Makefile includes
include ../../Makefile.inc
