# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += src/hcsr04.cpp
SRC += img/images.cpp

TARGET=HC-SR04
DEVICE=picopad10
DEVCLASS=picopad
DEVDIR=!PicoPad10

# Makefile includes
include ../../../Makefile.inc
