
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/tiles.cpp

SRC += snd/brick.cpp
SRC += snd/gameover.cpp
SRC += snd/levelup.cpp
SRC += snd/line.cpp

# Makefile includes
include ../../Makefile.inc
