
# ASM source files
ASRC += 

# C source files
CSRC +=

# C++ source files
SRC += src/data.cpp
SRC += src/game.cpp
SRC += src/main.cpp
SRC += src/open.cpp

SRC += img/logo.cpp
SRC += img/tiles.cpp
SRC += img/sprites.cpp
SRC += img/status.cpp

SRC += snd/startsnd.cpp
SRC += snd/siren.cpp
SRC += snd/wakka.cpp
SRC += snd/frighten.cpp
SRC += snd/eatghost.cpp
SRC += snd/eatfruit.cpp
SRC += snd/death.cpp
SRC += snd/extrapac.cpp
SRC += snd/intermission.cpp

# Makefile includes
include ../../Makefile.inc
