
# ASM source files
ASRC += 

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += img/tiles.cpp
SRC += snd/move.cpp
SRC += snd/bump.cpp
SRC += snd/shuffling.cpp
SRC += snd/fanfare.cpp

# Makefile includes
include ../../Makefile.inc
