
# ASM source files
ASRC += 

# C source files
CSRC +=

# C++ source files
SRC += src/balls.cpp
SRC += src/blueenemy.cpp
SRC += src/gameloop.cpp
SRC += src/gamemap.cpp
SRC += src/chicken.cpp
SRC += src/levels.cpp
SRC += src/main.cpp
SRC += src/mushroom.cpp
SRC += src/objects.cpp
SRC += src/random.cpp
SRC += src/redenemy.cpp
SRC += src/scene.cpp
SRC += src/select.cpp
SRC += src/solutions.cpp
SRC += src/tiles.cpp

SRC += img/intro.cpp
SRC += img/tilesimg.cpp

SRC += snd/music.cpp

# Makefile includes
include ../../Makefile.inc
