
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += img/forest.cpp
SRC += img/duck.cpp
SRC += snd/river.cpp

# Makefile includes
include ../../Makefile.inc
