
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/sprites.cpp

SRC += snd/tone1.cpp
SRC += snd/tone2.cpp
SRC += snd/tone3.cpp
SRC += snd/tone4.cpp
SRC += snd/shoot.cpp
SRC += snd/hit.cpp
SRC += snd/crash.cpp
SRC += snd/mother.cpp

# Makefile includes
include ../../Makefile.inc
