# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += src/SimpleDS3231.cpp
SRC += img/images.cpp

TARGET=DS3231
DEVICE=picopad10
DEVCLASS=picopad
DEVDIR=!PicoPad10

# Makefile includes
include ../../../Makefile.inc
