
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += img/repro1.cpp
SRC += img/repro2.cpp
SRC += img/repro3.cpp
SRC += snd/test.cpp

# Makefile includes
include ../../Makefile.inc
