
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += img/01.cpp
SRC += img/02.cpp
SRC += img/03.cpp
SRC += img/04.cpp
SRC += img/05.cpp
SRC += img/06.cpp
SRC += img/07.cpp
SRC += img/08.cpp
SRC += img/09.cpp
SRC += img/10.cpp
SRC += img/11.cpp
SRC += img/12.cpp
SRC += img/13.cpp
SRC += img/14.cpp
SRC += img/15.cpp
SRC += img/16.cpp
SRC += img/17.cpp
SRC += img/18.cpp
SRC += img/19.cpp
SRC += img/20.cpp
SRC += img/22.cpp

SRC += src/main.cpp

# Makefile includes
include ../../Makefile.inc
