
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += img/CobbleStone.cpp 
SRC += img/Fabric.cpp       
SRC += img/Soil.cpp         
SRC += img/Wood.cpp

SRC += src/main.cpp

# Makefile includes
include ../../Makefile.inc
