
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += snd/bound.cpp
SRC += snd/out.cpp
SRC += snd/paddle.cpp
SRC += snd/serve.cpp

# Makefile includes
include ../../Makefile.inc
