
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
#SRC += img/tiles.cpp
SRC += img/tiles_pal.cpp
SRC += img/skyline.cpp

SRC += img/car0.cpp
SRC += img/car1.cpp
SRC += img/car2.cpp
SRC += img/car3.cpp
SRC += img/car4.cpp
SRC += img/car5.cpp
SRC += img/car6.cpp
SRC += img/car7.cpp
SRC += img/car8.cpp
SRC += img/car9.cpp
SRC += img/car10.cpp
SRC += img/car11.cpp
SRC += img/car12.cpp
SRC += img/car13.cpp
SRC += img/car14.cpp
SRC += img/car15.cpp
SRC += img/car16.cpp

SRC += img/ghost0.cpp
SRC += img/ghost1.cpp
SRC += img/ghost2.cpp
SRC += img/ghost3.cpp
SRC += img/ghost4.cpp
SRC += img/ghost5.cpp
SRC += img/ghost6.cpp
SRC += img/ghost7.cpp

SRC += snd/engine.cpp

SRC += src/main.cpp

# Makefile includes
include ../../Makefile.inc
